project:
  type: website

website:
  title: "**A**ncient **O**ceans **L**ab"
  navbar:
    background: "#16555d"
    right:
      - href: research/index.qmd
        text: Research
      - href: team/index.qmd
        text: Team
      - href: data/index.qmd
        text: Data
      - text: Projects
        menu:
          - text: EDiTH
            href: projects/edith/index.qmd
      - text: Apps
        menu:
          - text: Diversity Dynamics
            href: https://edith-nerc.github.io/app/
      - href: news/index.qmd
        text: News
      - href: contact/index.qmd
        text: Contact
      - href: https://github.com/AncientOceansLab
        icon: github
      - href: https://bsky.app/profile/ancientoceans.bsky.social
        text: "{{< iconify fa6-brands bluesky >}}"
  page-footer: 
    background: "#16555d"
    border: "#16555d"
    left: "&copy; Copyright 2025, Lewis A. Jones" 
    right:
      - href: https://github.com/AncientOceansLab
        icon: github
      - href: https://bsky.app/profile/ancientoceans.bsky.social
        text: "{{< iconify fa6-brands bluesky >}}"

format:
  html:
    theme: 
     - yeti
    css: styles.css
    toc: true

editor: visual

