project:
  type: website

website:
  title: "Ancient Oceans Lab"
  navbar:
    right:
      - href: research/index.qmd
        text: Research
      - href: team/index.qmd
        text: Team
      - href: data/index.qmd
        text: Data
      - text: Projects
        menu:
          - text: EDiTH
            href: projects/edith/index.qmd
      - text: Apps
        menu:
          - text: Diversity Dynamics
            href: https://edith-nerc.github.io/app/
      - href: news/index.qmd
        text: News
      - href: contact/index.qmd
        text: Contact

format:
  html:
    theme: 
     - yeti
    css: styles.css
    toc: true

editor: visual

