project:
  type: website
  output-dir: docs

website:
  title: "Ancient Oceans Lab"
  navbar:
    right:
      - href: research.qmd
        text: Research
      - href: team.qmd
        text: Team
      - href: data.qmd
        text: Data
      - text: Projects
        menu:
          - text: EDiTH
            href: projects/edith.qmd
      - text: Apps
        menu:
          - text: Cenozoic Coral Diversity Dynamics
            href: https://edith-nerc.github.io/app/
      - href: news.qmd
        text: News
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: 
     - yeti
    css: styles.css
    toc: true

editor: visual

