project:
  type: website

website:
  title: "**A**ncient **O**ceans **L**ab"
  navbar:
    background: "#16555d"
    right:
      - text: Team
        href: team/index.qmd
      - text: Research
        menu:
          - text: Themes
            href: research/themes/index.qmd
          - text: Publications
            href: research/publications/index.qmd
      - text: Projects
        menu:
          - text: EDiTH
            href: projects/edith/index.qmd
      - text: Data
        href: data/index.qmd
      - text: Software
        menu:
          - text: Diversity Dynamics
            href: https://edith-nerc.github.io/app/
      - href: outreach/index.qmd
        text: Outreach
      - href: news/index.qmd
        text: News
      - href: contact/index.qmd
        text: Contact
      - href: https://github.com/AncientOceansLab
        icon: github
      - href: https://bsky.app/profile/ancientoceans.bsky.social
        text: "{{< iconify fa6-brands bluesky >}}"
  page-footer: 
    background: "#16555d"
    border: "#16555d"
    left: "&copy; Copyright 2025, Lewis A. Jones" 
    right:
      - href: https://github.com/AncientOceansLab
        icon: github
      - href: https://bsky.app/profile/ancientoceans.bsky.social
        text: "{{< iconify fa6-brands bluesky >}}"

format:
  html:
    theme: 
     - yeti
    css: styles.css
    toc: true

editor: visual

